dataset_name: water
num_train: 500
num_valid: 500

density_loss: 0.01
max_radius: 15.0

train_batch_size: 10
valid_batch_size: 10
test_batch_size: 10

learning_rate: 5e-4
weight_decay: 0.0
num_epochs: 100000
validation_interval: 100
use_gradient_clipping: true
clip_norm: 1.0
pin_memory: True
num_workers: 4
step_size: 10

num_bathes: 1000000
train_batch_interval: 100
validation_batch_interval: 1000
