# For hydra with version larger than 1.2.0
# override the internal parameters job.chdir for hydra to use various directories for logging
hydra:
  job:
    chdir: True

# build the conf. and conf.datasets
defaults:
  - _self_
  - datasets: QH9-dynamic

model: QHNet

ex_name: 'ex_name'
device: 0
ckpt_dir: 'checkpoints'
split_seed: 42
optimizer: adam
ema_start_epoch: -1


# download the pretrained model parameters automatically to the path
use_pretrained: True
pretrained_model_parameter_dir: '/tmp/QH9/pretrained_model_parameter_dir/'


# if not use pretrained model parameters, use the trained_model as the path to the parameters
trained_model: ''
# For evaluating trained model
seed: 0
